
name: Checks

on:
  push:
    branches: [ "develop" ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pycryptodome
          pip install flake8 Django coverage

      - name: Run Flake8 Lint and Check
        run: |
          flake8
          python manage.py check

      - name: Run Tests
        run: |
          coverage run manage.py test
